### ISSUE TITLE
Create axios two axios instance

### ISSUE THREAD

**Issue by Konson22** [Emmanuel-Melon/inspirers#30]
Create two axios instances public and private instance for data fetching
in private instance set withCredentials to true, and credentials:"include"

**Comment by Emmanuel-Melon** [comment]
> Create two axios instances public and private instance for data fetching in private instance set withCredentials to true, and credentials:"include"

AK, why do we need two axios instances? Can you elaborate on this? Also, have you taken a look at this file?

**Comment by Konson22** [comment]
1- It is more advantageous to use Axios with Axios. because it creates a new instance of Axios with a custom config.
2- Axios does more with less code. Unlike the Fetch API, you only need one .then() callback to access your requested JSON data.
