### ISSUE TITLE
Database Connection issue with PlanetScale

### ISSUE THREAD

**Issue by larrymiami** [Emmanuel-Melon/inspirers#51]
I was experiencing issues when setting up the project, copy-pasting the connection from PlanetScale, and setting it in my env file led to an error. After some research, I came across this [SOLUTION](https://github.com/planetscale/discussion/discussions/127)
Maybe you could include this change as you document
![image](https://user-images.githubusercontent.com/97871935/180005875-208f7b40-e1d5-4814-ab42-bc60265a4552.png)

**Comment by Emmanuel-Melon** [comment]
You need to install the planet scale cli
